[package]
name = "minigrep"
version = "0.1.0"
authors = ["Jason Erdmann <jason.erdmann@tradingtechnologies.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
clap    = "2.33.0"
